# Generated by Django 6.0.1 on 2026-01-21 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_bio_customuser_nickname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='year',
            field=models.IntegerField(blank=True, choices=[(1, 'First Year'), (2, 'Second Year'), (3, 'Third Year')], help_text='Year level (for students)', null=True),
        ),
    ]
