# Generated by Django 6.0.1 on 2026-01-21 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='stream',
            field=models.CharField(blank=True, choices=[('common_science', 'Common Science'), ('common_literature', 'Common Literature'), ('math', 'Math Stream'), ('science', 'Science Stream'), ('languages', 'Languages Stream'), ('literature', 'Literature Stream'), ('management_economics', 'Management & Economics Stream'), ('civil_engineering', 'Civil Engineering Stream')], help_text='Academic stream (for students)', max_length=50),
        ),
    ]
