# Generated by Django 6.0.1 on 2026-01-23 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customuser_stream'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='last_chat_clear_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
