# Generated by Django 6.0.1 on 2026-01-31 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_customuser_last_chat_clear_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='bio',
            field=models.TextField(blank=True, verbose_name='Bio'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_student',
            field=models.BooleanField(default=False, verbose_name='Is Student'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_teacher',
            field=models.BooleanField(default=False, verbose_name='Is Teacher'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='nickname',
            field=models.CharField(blank=True, max_length=50, verbose_name='Nickname'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/', verbose_name='Profile Picture'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='real_name',
            field=models.CharField(default='', max_length=100, verbose_name='Real Name'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='stream',
            field=models.CharField(blank=True, choices=[('common_science', 'Common Science'), ('common_literature', 'Common Literature'), ('math', 'Math Stream'), ('science', 'Science Stream'), ('languages', 'Languages Stream'), ('literature', 'Literature Stream'), ('management_economics', 'Management & Economics Stream'), ('civil_engineering', 'Civil Engineering Stream')], help_text='Academic stream (for students)', max_length=50, verbose_name='Stream'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='year',
            field=models.IntegerField(blank=True, choices=[(1, 'First Year'), (2, 'Second Year'), (3, 'Third Year')], help_text='Year level (for students)', null=True, verbose_name='Year'),
        ),
    ]
