# Generated by Django 6.0.1 on 2026-02-01 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_customuser_bio_alter_customuser_is_student_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='suspension_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
