# Generated by Django 6.0.1 on 2026-01-21 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='stream',
            field=models.CharField(choices=[('common_science', 'Common Science'), ('common_literature', 'Common Literature'), ('math', 'Math Stream'), ('science', 'Science Stream'), ('languages', 'Languages Stream'), ('literature', 'Literature Stream'), ('management_economics', 'Management & Economics Stream'), ('civil_engineering', 'Civil Engineering Stream')], default='common_science', max_length=50),
            preserve_default=False,
        ),
    ]
