# Generated by Django 6.0.1 on 2026-01-22 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_chatmessage_stream'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='stream',
            field=models.CharField(blank=True, choices=[('common_science', 'Common Science'), ('common_literature', 'Common Literature'), ('math', 'Math Stream'), ('science', 'Science Stream'), ('languages', 'Languages Stream'), ('literature', 'Literature Stream'), ('management_economics', 'Management & Economics Stream'), ('civil_engineering', 'Civil Engineering Stream')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='subject',
            field=models.CharField(blank=True, choices=[('math', 'Math'), ('science', 'Science'), ('physics', 'Physics'), ('arabic', 'Arabic'), ('english', 'English'), ('french', 'French'), ('hist_geo', 'History & Geography'), ('civil_eng', 'Civil Engineering'), ('accounting', 'Accounting'), ('law', 'Law'), ('economy', 'Economy'), ('german', 'German'), ('spanish', 'Spanish')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='year',
            field=models.IntegerField(blank=True, choices=[(1, 'First Year'), (2, 'Second Year'), (3, 'Third Year')], null=True),
        ),
        migrations.AddField(
            model_name='test',
            name='stream',
            field=models.CharField(blank=True, choices=[('common_science', 'Common Science'), ('common_literature', 'Common Literature'), ('math', 'Math Stream'), ('science', 'Science Stream'), ('languages', 'Languages Stream'), ('literature', 'Literature Stream'), ('management_economics', 'Management & Economics Stream'), ('civil_engineering', 'Civil Engineering Stream')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='test',
            name='subject',
            field=models.CharField(blank=True, choices=[('math', 'Math'), ('science', 'Science'), ('physics', 'Physics'), ('arabic', 'Arabic'), ('english', 'English'), ('french', 'French'), ('hist_geo', 'History & Geography'), ('civil_eng', 'Civil Engineering'), ('accounting', 'Accounting'), ('law', 'Law'), ('economy', 'Economy'), ('german', 'German'), ('spanish', 'Spanish')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='test',
            name='year',
            field=models.IntegerField(blank=True, choices=[(1, 'First Year'), (2, 'Second Year'), (3, 'Third Year')], null=True),
        ),
    ]
