# Generated by Django 6.0.1 on 2026-01-22 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_lesson_stream_lesson_subject_lesson_year_test_stream_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
