# Generated by Django 6.0.1 on 2026-01-23 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_test_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='lessons/pdfs/'),
        ),
        migrations.AddField(
            model_name='test',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='tests/pdfs/'),
        ),
    ]
