# Generated by Django 6.0.1 on 2026-01-24 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0011_result_feedback_date_result_teacher_feedback_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
