# Generated by Django 6.0.1 on 2026-01-24 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0014_notification_studentanswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumthread',
            name='category',
            field=models.CharField(choices=[('question', 'Question'), ('discussion', 'General Discussion'), ('resource', 'Resource Share')], default='discussion', max_length=20),
        ),
    ]
