# Generated by Django 6.0.1 on 2026-01-25 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0015_forumthread_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumthread',
            name='stream',
            field=models.CharField(blank=True, choices=[('common_science', 'Common Science'), ('common_literature', 'Common Literature'), ('math', 'Math Stream'), ('science', 'Science Stream'), ('languages', 'Languages Stream'), ('literature', 'Literature Stream'), ('management_economics', 'Management & Economics Stream'), ('civil_engineering', 'Civil Engineering Stream')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='forumthread',
            name='year',
            field=models.IntegerField(blank=True, choices=[(1, 'First Year'), (2, 'Second Year'), (3, 'Third Year')], null=True),
        ),
    ]
