# Generated by Django 6.0.1 on 2026-01-25 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0016_forumthread_stream_forumthread_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='announcement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='content.announcement'),
        ),
        migrations.AlterField(
            model_name='forumthread',
            name='subject',
            field=models.CharField(choices=[('math', 'Math'), ('science', 'Science'), ('physics', 'Physics'), ('arabic', 'Arabic'), ('english', 'English'), ('french', 'French'), ('hist_geo', 'History & Geography'), ('civil_eng', 'Civil Engineering'), ('accounting', 'Accounting'), ('law', 'Law'), ('economy', 'Economy'), ('german', 'German'), ('spanish', 'Spanish'), ('philosophy', 'Philosophy')], max_length=50),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='subject',
            field=models.CharField(blank=True, choices=[('math', 'Math'), ('science', 'Science'), ('physics', 'Physics'), ('arabic', 'Arabic'), ('english', 'English'), ('french', 'French'), ('hist_geo', 'History & Geography'), ('civil_eng', 'Civil Engineering'), ('accounting', 'Accounting'), ('law', 'Law'), ('economy', 'Economy'), ('german', 'German'), ('spanish', 'Spanish'), ('philosophy', 'Philosophy')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='resource',
            name='subject',
            field=models.CharField(blank=True, choices=[('math', 'Math'), ('science', 'Science'), ('physics', 'Physics'), ('arabic', 'Arabic'), ('english', 'English'), ('french', 'French'), ('hist_geo', 'History & Geography'), ('civil_eng', 'Civil Engineering'), ('accounting', 'Accounting'), ('law', 'Law'), ('economy', 'Economy'), ('german', 'German'), ('spanish', 'Spanish'), ('philosophy', 'Philosophy')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='subject',
            field=models.CharField(blank=True, choices=[('math', 'Math'), ('science', 'Science'), ('physics', 'Physics'), ('arabic', 'Arabic'), ('english', 'English'), ('french', 'French'), ('hist_geo', 'History & Geography'), ('civil_eng', 'Civil Engineering'), ('accounting', 'Accounting'), ('law', 'Law'), ('economy', 'Economy'), ('german', 'German'), ('spanish', 'Spanish'), ('philosophy', 'Philosophy')], max_length=50, null=True),
        ),
    ]
