# Generated by Django 6.0.1 on 2026-01-31 17:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0017_notification_announcement_alter_forumthread_subject_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='content',
            field=models.TextField(verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='message',
            field=models.TextField(verbose_name='Message'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='stream',
            field=models.CharField(choices=[('common_science', 'Common Science'), ('common_literature', 'Common Literature'), ('math', 'Math Stream'), ('science', 'Science Stream'), ('languages', 'Languages Stream'), ('literature', 'Literature Stream'), ('management_economics', 'Management & Economics Stream'), ('civil_engineering', 'Civil Engineering Stream')], max_length=50, verbose_name='Stream'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='year',
            field=models.IntegerField(choices=[(1, 'First Year'), (2, 'Second Year'), (3, 'Third Year')], verbose_name='Year'),
        ),
        migrations.AlterField(
            model_name='forumpost',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='forumpost',
            name='content',
            field=models.TextField(verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='forumpost',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='forumpost',
            name='thread',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='content.forumthread', verbose_name='Thread'),
        ),
        migrations.AlterField(
            model_name='forumthread',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='forumthread',
            name='category',
            field=models.CharField(choices=[('question', 'Question'), ('discussion', 'General Discussion'), ('resource', 'Resource Share')], default='discussion', max_length=20, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='forumthread',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='forumthread',
            name='stream',
            field=models.CharField(blank=True, choices=[('common_science', 'Common Science'), ('common_literature', 'Common Literature'), ('math', 'Math Stream'), ('science', 'Science Stream'), ('languages', 'Languages Stream'), ('literature', 'Literature Stream'), ('management_economics', 'Management & Economics Stream'), ('civil_engineering', 'Civil Engineering Stream')], max_length=50, null=True, verbose_name='Stream'),
        ),
        migrations.AlterField(
            model_name='forumthread',
            name='subject',
            field=models.CharField(choices=[('math', 'Math'), ('science', 'Science'), ('physics', 'Physics'), ('arabic', 'Arabic'), ('english', 'English'), ('french', 'French'), ('hist_geo', 'History & Geography'), ('civil_eng', 'Civil Engineering'), ('accounting', 'Accounting'), ('law', 'Law'), ('economy', 'Economy'), ('german', 'German'), ('spanish', 'Spanish'), ('philosophy', 'Philosophy')], max_length=50, verbose_name='Subject'),
        ),
        migrations.AlterField(
            model_name='forumthread',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='forumthread',
            name='year',
            field=models.IntegerField(blank=True, choices=[(1, 'First Year'), (2, 'Second Year'), (3, 'Third Year')], null=True, verbose_name='Year'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to=settings.AUTH_USER_MODEL, verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='content',
            field=models.TextField(verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='Is Approved'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='lessons/pdfs/', verbose_name='PDF File'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='stream',
            field=models.CharField(blank=True, choices=[('common_science', 'Common Science'), ('common_literature', 'Common Literature'), ('math', 'Math Stream'), ('science', 'Science Stream'), ('languages', 'Languages Stream'), ('literature', 'Literature Stream'), ('management_economics', 'Management & Economics Stream'), ('civil_engineering', 'Civil Engineering Stream')], max_length=50, null=True, verbose_name='Stream'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='subject',
            field=models.CharField(blank=True, choices=[('math', 'Math'), ('science', 'Science'), ('physics', 'Physics'), ('arabic', 'Arabic'), ('english', 'English'), ('french', 'French'), ('hist_geo', 'History & Geography'), ('civil_eng', 'Civil Engineering'), ('accounting', 'Accounting'), ('law', 'Law'), ('economy', 'Economy'), ('german', 'German'), ('spanish', 'Spanish'), ('philosophy', 'Philosophy')], max_length=50, null=True, verbose_name='Subject'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='year',
            field=models.IntegerField(blank=True, choices=[(1, 'First Year'), (2, 'Second Year'), (3, 'Third Year')], null=True, verbose_name='Year'),
        ),
        migrations.AlterField(
            model_name='lessoncomment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='lessoncomment',
            name='content',
            field=models.TextField(verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='lessoncomment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='lessoncomment',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='content.lesson', verbose_name='Lesson'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='announcement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='content.announcement', verbose_name='Announcement'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='is_read',
            field=models.BooleanField(default=False, verbose_name='Is Read'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='link',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Link'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='message',
            field=models.TextField(verbose_name='Message'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Recipient'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='question',
            name='correct_option',
            field=models.CharField(choices=[('A', 'Option A'), ('B', 'Option B'), ('C', 'Option C'), ('D', 'Option D')], max_length=1, verbose_name='Correct Option'),
        ),
        migrations.AlterField(
            model_name='question',
            name='option_a',
            field=models.CharField(max_length=200, verbose_name='Option A'),
        ),
        migrations.AlterField(
            model_name='question',
            name='option_b',
            field=models.CharField(max_length=200, verbose_name='Option B'),
        ),
        migrations.AlterField(
            model_name='question',
            name='option_c',
            field=models.CharField(max_length=200, verbose_name='Option C'),
        ),
        migrations.AlterField(
            model_name='question',
            name='option_d',
            field=models.CharField(max_length=200, verbose_name='Option D'),
        ),
        migrations.AlterField(
            model_name='question',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='content.test', verbose_name='Test'),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.CharField(max_length=500, verbose_name='Question Text'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='resources/files/', verbose_name='File'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='Is Approved'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='stream',
            field=models.CharField(blank=True, choices=[('common_science', 'Common Science'), ('common_literature', 'Common Literature'), ('math', 'Math Stream'), ('science', 'Science Stream'), ('languages', 'Languages Stream'), ('literature', 'Literature Stream'), ('management_economics', 'Management & Economics Stream'), ('civil_engineering', 'Civil Engineering Stream')], max_length=50, null=True, verbose_name='Stream'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='subject',
            field=models.CharField(blank=True, choices=[('math', 'Math'), ('science', 'Science'), ('physics', 'Physics'), ('arabic', 'Arabic'), ('english', 'English'), ('french', 'French'), ('hist_geo', 'History & Geography'), ('civil_eng', 'Civil Engineering'), ('accounting', 'Accounting'), ('law', 'Law'), ('economy', 'Economy'), ('german', 'German'), ('spanish', 'Spanish'), ('philosophy', 'Philosophy')], max_length=50, null=True, verbose_name='Subject'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='type',
            field=models.CharField(choices=[('pdf', 'PDF Document'), ('video', 'Video Link'), ('link', 'External Link')], max_length=10, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='year',
            field=models.IntegerField(blank=True, choices=[(1, 'First Year'), (2, 'Second Year'), (3, 'Third Year')], null=True, verbose_name='Year'),
        ),
        migrations.AlterField(
            model_name='result',
            name='date_taken',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date Taken'),
        ),
        migrations.AlterField(
            model_name='result',
            name='feedback_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Feedback Date'),
        ),
        migrations.AlterField(
            model_name='result',
            name='score',
            field=models.IntegerField(verbose_name='Score'),
        ),
        migrations.AlterField(
            model_name='result',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to=settings.AUTH_USER_MODEL, verbose_name='Student'),
        ),
        migrations.AlterField(
            model_name='result',
            name='teacher_feedback',
            field=models.TextField(blank=True, null=True, verbose_name='Teacher Feedback'),
        ),
        migrations.AlterField(
            model_name='result',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='content.test', verbose_name='Test'),
        ),
        migrations.AlterField(
            model_name='result',
            name='total_questions',
            field=models.IntegerField(verbose_name='Total Questions'),
        ),
        migrations.AlterField(
            model_name='studentanswer',
            name='is_correct',
            field=models.BooleanField(default=False, verbose_name='Is Correct'),
        ),
        migrations.AlterField(
            model_name='studentanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.question', verbose_name='Question'),
        ),
        migrations.AlterField(
            model_name='studentanswer',
            name='result',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='content.result', verbose_name='Result'),
        ),
        migrations.AlterField(
            model_name='studentanswer',
            name='selected_option',
            field=models.CharField(max_length=1, verbose_name='Selected Option'),
        ),
        migrations.AlterField(
            model_name='test',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to=settings.AUTH_USER_MODEL, verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='test',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='test',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='test',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='Is Approved'),
        ),
        migrations.AlterField(
            model_name='test',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='tests/pdfs/', verbose_name='PDF File'),
        ),
        migrations.AlterField(
            model_name='test',
            name='stream',
            field=models.CharField(blank=True, choices=[('common_science', 'Common Science'), ('common_literature', 'Common Literature'), ('math', 'Math Stream'), ('science', 'Science Stream'), ('languages', 'Languages Stream'), ('literature', 'Literature Stream'), ('management_economics', 'Management & Economics Stream'), ('civil_engineering', 'Civil Engineering Stream')], max_length=50, null=True, verbose_name='Stream'),
        ),
        migrations.AlterField(
            model_name='test',
            name='subject',
            field=models.CharField(blank=True, choices=[('math', 'Math'), ('science', 'Science'), ('physics', 'Physics'), ('arabic', 'Arabic'), ('english', 'English'), ('french', 'French'), ('hist_geo', 'History & Geography'), ('civil_eng', 'Civil Engineering'), ('accounting', 'Accounting'), ('law', 'Law'), ('economy', 'Economy'), ('german', 'German'), ('spanish', 'Spanish'), ('philosophy', 'Philosophy')], max_length=50, null=True, verbose_name='Subject'),
        ),
        migrations.AlterField(
            model_name='test',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='test',
            name='year',
            field=models.IntegerField(blank=True, choices=[(1, 'First Year'), (2, 'Second Year'), (3, 'Third Year')], null=True, verbose_name='Year'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['year', 'stream', 'created_at'], name='content_cha_year_b318b6_idx'),
        ),
    ]
