# Generated by Django 6.0.1 on 2026-02-01 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0018_alter_announcement_author_alter_announcement_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumthread',
            name='is_removed',
            field=models.BooleanField(default=False, verbose_name='Is Removed'),
        ),
    ]
