# Generated by Django 6.0.1 on 2026-02-01 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0019_forumthread_is_removed'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='is_removed',
            field=models.BooleanField(default=False, verbose_name='Is Removed'),
        ),
        migrations.AddField(
            model_name='forumpost',
            name='is_removed',
            field=models.BooleanField(default=False, verbose_name='Is Removed'),
        ),
        migrations.AddField(
            model_name='lessoncomment',
            name='is_removed',
            field=models.BooleanField(default=False, verbose_name='Is Removed'),
        ),
    ]
