# Generated by Django 6.0.1 on 2026-02-01 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0020_chatmessage_is_removed_forumpost_is_removed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='is_removed',
            field=models.BooleanField(default=False, verbose_name='Is Removed'),
        ),
        migrations.AddField(
            model_name='resource',
            name='is_removed',
            field=models.BooleanField(default=False, verbose_name='Is Removed'),
        ),
        migrations.AddField(
            model_name='test',
            name='is_removed',
            field=models.BooleanField(default=False, verbose_name='Is Removed'),
        ),
    ]
