# Generated by Django 6.0.1 on 2026-02-01 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0021_lesson_is_removed_resource_is_removed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='is_removed',
            field=models.BooleanField(default=False, verbose_name='Is Removed'),
        ),
        migrations.AddField(
            model_name='notification',
            name='is_removed',
            field=models.BooleanField(default=False, verbose_name='Is Removed'),
        ),
        migrations.AddField(
            model_name='question',
            name='is_removed',
            field=models.BooleanField(default=False, verbose_name='Is Removed'),
        ),
    ]
